import { StyleSheet } from 'react-native';
import { colors } from './colors';

export const gameStyles = StyleSheet.create({
	container: {
		flex: 1,
		backgroundColor: colors.background,
		alignItems: 'center',
		justifyContent: 'center',
		padding: 16,
		gap: 12,
	},
	title: {
		color: colors.text,
		fontSize: 36,
		fontWeight: 'bold',
		marginBottom: 16,
		letterSpacing: 1.2,
	},
	modeRow: {
		flexDirection: 'row',
		marginBottom: 12,
		gap: 8,
	},
	notFoundContainer: {
		flex: 1,
		alignItems: 'center',
		justifyContent: 'center',
		backgroundColor: colors.background,
		padding: 32,
		gap: 12,
	},
	notFoundTitle: {
		fontSize: 30,
		fontWeight: 'bold',
		color: colors.accent,
		marginBottom: 18,
		letterSpacing: 1.1,
	},
	notFoundMessage: {
		fontSize: 18,
		color: colors.text,
		textAlign: 'center',
		lineHeight: 28,
		opacity: 0.9,
	},
	round: {
		color: colors.text,
		fontSize: 22,
		marginBottom: 4,
		fontWeight: '600',
	},
	shape: {
		color: '#aaa',
		fontSize: 16,
		marginBottom: 8,
		fontStyle: 'italic',
	},
	narration: {
		color: colors.text,
		fontSize: 17,
		marginBottom: 18,
		textAlign: 'center',
		minHeight: 40,
		opacity: 0.85,
	},
	streak: {
		color: colors.accent,
		fontSize: 22,
		fontWeight: 'bold',
		marginBottom: 6,
		letterSpacing: 0.5,
	},
	cosmetics: {
		marginTop: 18,
		marginBottom: 18,
		alignItems: 'center',
		gap: 6,
	},
	cosmeticsTitle: {
		color: colors.accent,
		fontSize: 20,
		fontWeight: 'bold',
		marginBottom: 8,
		letterSpacing: 0.5,
	},
	cosmeticItem: {
		color: colors.text,
		fontSize: 16,
		marginBottom: 4,
		paddingHorizontal: 8,
		paddingVertical: 2,
		borderRadius: 8,
		backgroundColor: '#222',
		marginRight: 6,
	},
	choices: {
		marginTop: 18,
		marginBottom: 18,
		alignItems: 'center',
		gap: 8,
	},
	choicesTitle: {
		color: colors.accent,
		fontSize: 20,
		fontWeight: 'bold',
		marginBottom: 8,
		letterSpacing: 0.5,
	},
	buttonRow: {
		flexDirection: 'row',
		justifyContent: 'center',
		marginVertical: 14,
		gap: 8,
	},
	buttonWrapper: {
		marginHorizontal: 8,
		borderRadius: 8,
		overflow: 'hidden',
		shadowColor: '#000',
		shadowOpacity: 0.12,
		shadowRadius: 4,
		elevation: 2,
	},
	scoreboardContainer: {
		marginTop: 28,
		backgroundColor: '#222',
		borderRadius: 14,
		padding: 18,
		alignItems: 'center',
		gap: 8,
		shadowColor: '#000',
		shadowOpacity: 0.1,
		shadowRadius: 6,
		elevation: 3,
	},
	scoreboardTitle: {
		color: colors.accent,
		fontSize: 22,
		fontWeight: 'bold',
		marginBottom: 12,
		letterSpacing: 0.5,
	},
	scoreboardRow: {
		flexDirection: 'row',
		justifyContent: 'space-between',
		width: 220,
		marginBottom: 6,
		gap: 4,
	},
	scoreboardRank: {
		color: colors.accent,
		fontWeight: 'bold',
		width: 30,
		fontSize: 16,
	},
	scoreboardName: {
		color: colors.text,
		width: 120,
		fontSize: 16,
	},
	scoreboardScore: {
		color: colors.text,
		width: 50,
		textAlign: 'right',
		fontSize: 16,
	},
});
